add new pair

diff --git a/libexec/setzer/setzer-x-price b/libexec/setzer/setzer-x-price
--- a/libexec/setzer/setzer-x-price
+++ b/libexec/setzer/setzer-x-price
@@ -319,6 +319,20 @@ case $src in
     json=$(curl -sS "https://api.probit.com/api/exchange/v1/ticker?market_ids=${base^^}-${quote^^}")
     setzer --format "$(jshon <<<"$json" -e data -e 0 -e last -u)"
   };;
+  velero_price__wagyu) {
+    case "${pair^^}" in
+      BUSDUSD|BUSD:USD) {
+        first_token="0xcd7509b76281223f5b7d3ad5d47f8d7aa5c2b9bf"
+        second_token="0xc111c29A988AE0C0087D97b33C6E6766808A3BD3"
+        amount="1000000000000000000"
+      };;
+      *) {
+        echo >&2 "Error: pair(${pair^^}) not recognised for this source (${src}): "
+      };;
+    esac
+    json=$(curl -sS "https://price.velero.finance/v1/wagyu/price?first_token=${first_token}&second_token=${second_token}&amount=${amount}")
+    setzer --format "$(jshon <<<"$json" -e result -e price -u)"
+  };;
   *) {
     echo >&2 "Error: exchange not recognised: $src"
   };;
